config/routes.rb
Travel::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root :to => "main#index"
  match '/login' => 'main#login', :via => :get
  match '/logout' => 'main#logout', :via => :get
  match '/signup' => 'main#signup', :via => :get
  resources :main do
    member do
      get 'show_tejia'
      get 'show_rm'
      get 'show_classic'
      get 'show_chujing'
      get 'show_domestic'
      get 'show_raider'
      get 'visa_show'
    end
    collection do
      post 'user_create'
      post 'login_check'
      get 'check_login'
      get 'visa'
    end
  end
  resources :destination_one do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :destination_two do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :destination_three do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :destination_four do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :destination_five do
    collection do
      post 'user_create'
    end
  end

  resources :destination_six

  resources :destination_seven

  resources :destination_eight do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :cities do
    collection do
      get 'xianggang'
      get 'aomen'
      get 'gangao'
      get 'feizhou'
      get 'remenchujing'
      get 'remenhaidao'
      get 'dongnanya'
      get 'yazhou'
      get 'ouzhou'
      get 'meizhou'
      get 'zhongdongfeizhou'
      get 'aozhou'
      get 'remenguonei'
      get 'huanan'
      get 'xinan'
      get 'huadong'
      get 'huazhong'
      get 'huabei'
      get 'xibu'
      get 'dongbei'
      get 'changchun'
    end
  end
  namespace :admin do
    match '' => 'accounts#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end

    resources :accounts do
      collection do
        post 'update_multiple'
      end
    end

    resources :announcements

    resources :raiders

    resources :one_cities do
      resources :exithots
      resources :domestics
      resources :jingdians
      resources :hotdoors
    end

    resources :citys do
      resources :tejia
      resources :raiders
      resources :recommends
      resources :gentuans
      resources :freelines
    end

    resources :three_cities do
      resources :three_tejia
      resources :three_raiders
      resources :three_recommends
      resources :three_gentuans
      resources :three_freelines
    end
    resources :companies do
      collection do
        get 'hotline'
        get 'customized_packages'
      end
    end
    resources :taiguos

    resources :hotels do
      resources :occupancy_hotels
    end

    resources :visas

    resources :addcities do
      resources :addtravels
    end
  end

end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::MainController
  layout 'admin'

  def index
  end

  def new
    @hotline = Hotline.new
  end

  def show
    @hotline = Hotline.find params[:id]
  end

  def create
    if request.post?
      if params[:hotline]
        avatar = params[:hotline][:avatar]
        title = params[:hotline][:title]
        description = params[:hotline][:description]
        price = params[:hotline][:price]
        xingcheng = params[:hotline][:xingcheng]
        feiyongshuoming = params[:hotline][:feiyongshuoming]
        wenxintishi = params[:hotline][:wenxintishi]
        yudingtishi = params[:hotline][:yudingtishi]
        imagename = avatar.original_filename
        avatar.original_filename = Time.now.strftime("%Y%m%d%h%m%s")<<rand(99999).to_s<<imagename[imagename.length-4, 4]
        if !avatar.blank? && !title.blank? && !description.blank? && !price.blank? && !xingcheng.blank? && !feiyongshuoming.blank? && !wenxintishi.blank? && !yudingtishi.blank?
          rc = Hotline.create(
              :avatar => avatar,
              :title => title,
              :description => description,
              :price => price,
              :xingcheng => xingcheng,
              :feiyongshuoming => feiyongshuoming,
              :wenxintishi => wenxintishi,
              :yudingtishi => yudingtishi
          )
          if rc.valid?
          else
            flash[:note]="创建成功！"
            redirect_to :back and return
          end
          redirect_to hotline_admin_companies_path and return
        else
          flash[:note]="添加失败，请检查添加项是否有空值！"
          redirect_to :back
        end
      end
    end
  end

  def edit
  end

  # 热门路线
  def hotline
    @hl = Hotline.order_ct_desc.page(params[:page]).per(10)
  end

  # 定制包团
  def customized_packages
    @cp = Customized.order_ct_desc.page(params[:page]).per(10)
  end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/views/admin/companies/customized_packages.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      公司包团列表
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title>
      <h2><i class="icon-list-alt"></i> 公司包团列表</h2>
    </div>
    <div class="box-content">
      <table class="table table-striped table-bordered bootstrap-datatable datatable">
        <thead>
        <tr>
          <th>ID</th>
          <th>公司名称</th>
          <th>联系人</th>
          <th>电话号</th>
          <th>包团电话</th>
          <th>包团时间</th>
        </tr>
        </thead>
        <tbody>
        <% @cp.each do |q| %>
            <tr>
              <td><%= q.id %></td>
              <td><%= q.company_name %></td>
              <td><%= q.name %></td>
              <td><%= q.tell %></td>
              <td><%= q.caltel %></td>
              <td class="center"><%= my_datetime_format q.created_at %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination pagination-centered">
        <ul>
          <%= paginate @cp %>
        </ul>
      </div>
    </div>
  </div>
  <!--/span-->
</div><!--/row-->

app/views/admin/companies/edit.html.erb
<h1>Admin::Companies#edit</h1>
<p>Find me in app/views/admin/companies/edit.html.erb</p>

app/views/admin/companies/hotline.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      公司旅游路线管理
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title>
      <h2><i class="icon-list-alt"></i> 公司旅游路线管理</h2>
    </div>
    <div class="form-actions">
      <div style="float: left">
        <%= link_to '添加路线', new_admin_company_path, :class => "btn btn-primary" %>
      </div>
    </div>
    <div class="box-content">
      <table class="table table-striped table-bordered bootstrap-datatable datatable">
        <thead>
        <tr>
          <th>ID</th>
          <th>标题</th>
          <th>价格</th>
          <th>图片</th>
          <th>时间</th>
          <th>浏览</th>
          <th>修改</th>
        </tr>
        </thead>
        <tbody>
        <% @hl.each do |q| %>
            <tr>
              <td><%= q.id %></td>
              <td><%= q.title %></td>
              <td><%= q.price %></td>
              <td><%= image_tag q.avatar.url(:thumb) %></td>
              <td class="center"><%= my_datetime_format q.created_at %></td>
              <td><%= link_to '浏览', admin_company_path(q), :class => "btn btn-primary" %></td>
              <td><%= link_to '修改', edit_admin_company_path(q), :class => "btn btn-primary" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination pagination-centered">
        <ul>
          <%= paginate @hl %>
        </ul>
      </div>
    </div>
  </div>
  <!--/span-->
</div><!--/row-->

app/views/admin/companies/index.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      公司旅游管理
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title>
      <h2><i class="icon-list-alt"></i> 公司旅游管理</h2>
    </div>
    <div class="box-content">
      <div class="form-actions">
        <div style="float: left">
          <%= link_to '公司旅游路线', hotline_admin_companies_path, :class => "btn btn-primary" %>
        </div>
      </div>
      <div class="form-actions">
        <div style="float: left">
          <%= link_to '公司包团列表', customized_packages_admin_companies_path, :class => "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <!--/span-->
</div><!--/row-->

app/views/admin/companies/new.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_one_cities_path %>"> 世界游管理</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= hotline_admin_companies_path %>">公司旅游路线管理</a> <span class="divider">/</span>
    </li>
    <li>
      新建公司旅游路线
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 新建公司旅游路线</h2>
    </div>
    <div class="box-content">
      <%= form_for(:hotline, :url => admin_companies_path, :method => :post, :html => {:id => "verifytitle"}) do |f| %>
          <legend>新建公司旅游路线</legend>
          <h1><%= f.label "旅游标题：" %></h1>
          <%= f.text_field :title %>
          <br/>

          <h1><%= f.label "包团价格：" %></h1>
          <%= f.text_field :price %>
          <br/>

          <h1><%= f.label "旅游图片：" %></h1>
          <%= f.file_field :avatar %>
          <br/><br/>

          <h1><%= f.label "旅游内容：" %></h1>
          <%= f.text_area :description, :style => "width:99%;height:100px" %>
          <br/>

          <h1><%= f.label "参考行程：" %></h1>
          <%= f.cktext_area :xingcheng, :cols => 10, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'} %>
          <br/>

          <h1><%= f.label "费用说明：" %></h1>
          <%= f.cktext_area :feiyongshuoming, :cols => 10, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'} %>
          <br/>

          <h1><%= f.label "温馨提示：" %></h1>
          <%= f.cktext_area :wenxintishi, :cols => 10, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'} %>
          <br/>

          <h1><%= f.label "预订提示：" %></h1>
          <%= f.cktext_area :yudingtishi, :cols => 10, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'} %>

          <div class="form-actions">
            <button type="submit" class="btn btn-primary">完成提交</button>
          </div>
      <% end %>
    </div>
  </div>
  <!--/span-->
</div>
<script src="/admin/js/jquery.validate.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $("#verifytitle").validate({
                rules: {
                    "hotline[title]": {
                        required: true
                    },
                    "hotline[price]": {
                        required: true
                    },
                    "hotline[avatar]": {
                        required: true,
                        accept: "jpg|png"
                    },
                    "hotline[description]": {
                        required: true
                    }
                },
                messages: {
                    "hotline[title]": {
                        required: "“请填写标题”"
                    },
                    "hotline[price]": {
                        required: "“请填写价格”"
                    },
                    "hotline[avatar]": {
                        required: "“请上传图片”",
                        accept: "图片类型必须是png或jpg"
                    },
                    "hotline[description]": {
                        required: "“请填写内容”"
                    }
                },
                errorClass: "error",
                highlight: function (element, errorClass) {
                    $(element).parent().parent().addClass(errorClass);
                },
                unhighlight: function (element, errorClass) {
                    $(element).parent().parent().removeClass(errorClass);
                },
                errorPlacement: function (error, element) {
                    error.appendTo(element.parent());
                },
                errorElement: "span"
            });
        });
    });
    $(document).ready(function () {
        $('form[data-remote]').bind('ajax:before', function () {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        });
    });
</script>

app/views/admin/companies/show.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_one_cities_path %>"> 世界游管理</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= hotline_admin_companies_path %>">公司旅游路线管理</a> <span class="divider">/</span>
    </li>
    <li>
      公司旅游路线
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 公司旅游路线</h2>
    </div>
    <div class="box-content">
      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">旅游标题：
            <%= @hotline.title %>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>

      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">包团价格：
            <%= @hotline.price %>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>

      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">旅游图片：
            <%= image_tag @hotline.avatar.url(:show) %>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>

      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">旅游内容：
            <%= @hotline.description %>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>

      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">参考行程：
            <div class="form-actions">
              <%= @hotline.xingcheng.html_safe %>
            </div>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>


      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">费用说明：
            <div class="form-actions">
              <%= @hotline.feiyongshuoming.html_safe %>
            </div>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>

      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">温馨提示：
            <div class="form-actions">
              <%= @hotline.wenxintishi.html_safe %>
            </div>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>

      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">预订提示：
            <div class="form-actions">
              <%= @hotline.yudingtishi.html_safe %>
            </div>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>
    </div>
  </div>
  <!--/span-->
</div>