config/routes.rb
Travel::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root :to => "main#index"
  match '/login' => 'main#login', :via => :get
  match '/logout' => 'main#logout', :via => :get
  match '/signup' => 'main#signup', :via => :get
  resources :main do
    member do
      get 'show_tejia'
      get 'show_rm'
      get 'show_classic'
      get 'show_chujing'
      get 'show_domestic'
      get 'show_raider'
      get 'visa_show'
    end
    collection do
      post 'user_create'
      post 'login_check'
      get 'check_login'
      get 'visa'
    end
  end
  resources :destination_one do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :destination_two do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :destination_three do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :destination_four do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :destination_five do
    collection do
      post 'user_create'
    end
  end

  resources :destination_six

  resources :destination_seven

  resources :destination_eight do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :cities do
    collection do
      get 'xianggang'
      get 'aomen'
      get 'gangao'
      get 'feizhou'
      get 'remenchujing'
      get 'remenhaidao'
      get 'dongnanya'
      get 'yazhou'
      get 'ouzhou'
      get 'meizhou'
      get 'zhongdongfeizhou'
      get 'aozhou'
      get 'remenguonei'
      get 'huanan'
      get 'xinan'
      get 'huadong'
      get 'huazhong'
      get 'huabei'
      get 'xibu'
      get 'dongbei'
      get 'changchun'
    end
  end
  namespace :admin do
    match '' => 'accounts#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end

    resources :accounts do
      collection do
        post 'update_multiple'
      end
    end

    resources :announcements

    resources :raiders

    resources :one_cities do
      resources :exithots
      resources :domestics
      resources :jingdians
      resources :hotdoors
    end

    resources :citys do
      resources :tejia
      resources :raiders
      resources :recommends
      resources :gentuans
      resources :freelines
    end

    resources :three_cities do
      resources :three_tejia
      resources :three_raiders
      resources :three_recommends
      resources :three_gentuans
      resources :three_freelines
    end
    resources :companies do
      collection do
        get 'hotline'
        get 'customized_packages'
      end
    end
    resources :taiguos

    resources :hotels do
      resources :occupancy_hotels
    end

    resources :visas

    resources :addcities do
      resources :addtravels
    end
  end

end

app/models/addcity.rb
class Addcity < ActiveRecord::Base
  scope :order_ct_desc, lambda { order("created_at DESC") }
  validates :title, :presence => {:message => "标题不能为空"}

  QUESTION_CATEGORYS = [["未分类", 0], ["香港游", 100], ["澳门游", 101], ["港澳游", 102], ["非洲", 103],
                        ["热门出境", 1], ["热门海岛", 2], ["东南亚", 3], ["亚洲", 4], ["欧洲", 5], ["美洲", 6], ["中东非洲", 7], ["澳洲", 8],
                        ["热门国内", 9], ["华南", 10], ["西南", 11], ["华东", 12], ["华中", 13], ["华北", 14], ["西部", 15], ["东北", 16], ["长春", 17]]
  has_many :traves

  def Addcity.question_category_name(category_id)
    QUESTION_CATEGORYS.each do |item|
      return item[0] if item[1] == category_id
    end
  end

  def question_category_name
    Addcity.question_category_name(self.question_category_id)
  end
end

app/controllers/admin/addcities_controller.rb
class Admin::AddcitiesController < Admin::MainController
  layout 'admin'

  def index
    @jobs = Addcity.order_ct_desc.page(params[:page]).per(10)
  end

  def new
    @job = Addcity.new
  end

  def create
    @job = Addcity.new(
        :title => params[:addcity][:title],
        :question_category_id => params[:addcity][:question_category_id]
    )
    if @job.save
      flash[:error_msg] = "创建成功"
      redirect_to admin_addcities_path and return
    else
      flash[:error_msg] = @job.errors.values.join(";    ")
      redirect_to :back and return
    end
  end

  def edit
    @addcity = Addcity.find(params[:id])
  end

  def update
    @addcity = Addcity.find(params[:id])
    update_category = @addcity.update_attributes(
        :title => params[:addcity][:title]
    )
    if update_category
      respond_to do |category|
        category.html {
          redirect_to admin_addcities_path and return
        }
      end
    end
  end
end

app/helpers/admin/addcities_helper.rb
module Admin::AddcitiesHelper
end

app/views/admin/addcities/add_travel.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= travel_admin_addcity_path %>">旅游路线管理</a> <span class="divider">/</span>
    </li>
    <li>
      新建旅游内容
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 新建旅游内容</h2>
    </div>
    <div class="box-content">
      <%= form_for(:trave, :url => create_travel_admin_addcity_path, :method => :post, :html => {:id => "verifytitle"}) do |f| %>
          <legend>新建旅游内容</legend>
          <h1><%= f.label "旅游标题：" %></h1>
          <%= f.text_field :title %>
          <br/>

          <h1><%= f.label "旅游价格：" %></h1>
          <%= f.text_field :price %>
          <br/>

          <h1><%= f.label "旅游图片：" %></h1>
          <%= f.file_field :avatar %>
          <br/><br/>

          <h1><%= f.label "出发班期：" %></h1>
          <%= f.file_field :avatar1 %>
          <br/><br/>

          <h1><%= f.label "旅游内容：" %></h1>
          <%= f.text_area :description, :style => "width:99%;height:100px" %>
          <br/>

          <h1><%= f.label "参考行程：" %></h1>
          <%= f.cktext_area :xingcheng, :cols => 10, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'} %>
          <br/>

          <h1><%= f.label "费用说明：" %></h1>
          <%= f.cktext_area :feiyongshuoming, :cols => 10, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'} %>
          <br/>

          <h1><%= f.label "温馨提示：" %></h1>
          <%= f.cktext_area :wenxintishi, :cols => 10, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'} %>
          <br/>

          <h1><%= f.label "预订提示：" %></h1>
          <%= f.cktext_area :yudingtishi, :cols => 10, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'} %>

          <div class="form-actions">
            <button type="submit" class="btn btn-primary">完成提交</button>
          </div>
      <% end %>
    </div>
  </div>
  <!--/span-->
</div>
<script src="/admin/js/jquery.validate.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $("#verifytitle").validate({
                rules: {
                    "trave[title]": {
                        required: true
                    },
                    "trave[price]": {
                        required: true
                    },
                    "trave[avatar]": {
                        required: true,
                        accept: "jpg|png"
                    },
                    "trave[description]": {
                        required: true
                    }
                },
                messages: {
                    "trave[title]": {
                        required: "“请填写标题”"
                    },
                    "trave[price]": {
                        required: "“请填写价格”"
                    },
                    "trave[avatar]": {
                        required: "“请上传图片”",
                        accept: "图片类型必须是png或jpg"
                    },
                    "trave[description]": {
                        required: "“请填写内容”"
                    }
                },
                errorClass: "error",
                highlight: function (element, errorClass) {
                    $(element).parent().parent().addClass(errorClass);
                },
                unhighlight: function (element, errorClass) {
                    $(element).parent().parent().removeClass(errorClass);
                },
                errorPlacement: function (error, element) {
                    error.appendTo(element.parent());
                },
                errorElement: "span"
            });
        });
    });
    $(document).ready(function () {
        $('form[data-remote]').bind('ajax:before', function () {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        });
    });
</script>

app/views/admin/addcities/edit.html.erb
<script>
    <% if flash[:error_msg]%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_addcities_path %>">旅游管理</a> <span class="divider">/</span>
    </li>
    <li>
      修改旅游城市
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 修改旅游城市</h2>
    </div>
    <div class="box-content">
      <%= form_tag admin_addcity_path, :method => :put, :html => {:id => "verifytitle"} do %>
          <legend>修改旅游城市</legend>
          <p>
            <label>城市名称:</label>
            <input class="big-input" id="title" name="addcity[title]" size="30" type="text" value="<%= @addcity.title %>"/>
          </p>

          <div class="form-actions">
            <button type="submit" class="btn btn-primary">完成提交</button>
          </div>
      <% end %>
    </div>
  </div>
  <!--/span-->
</div>
<script src="/admin/js/jquery.validate.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $("#verifytitle").validate({
                rules: {
                    "hotel[title]": {
                        required: true
                    }
                },
                messages: {
                    "hotel[title]": {
                        required: "“请填写标题”"
                    }
                },
                errorClass: "error",
                highlight: function (element, errorClass) {
                    $(element).parent().parent().addClass(errorClass);
                },
                unhighlight: function (element, errorClass) {
                    $(element).parent().parent().removeClass(errorClass);
                },
                errorPlacement: function (error, element) {
                    error.appendTo(element.parent());
                },
                errorElement: "span"
            });
        });
    });
    $(document).ready(function () {
        $('form[data-remote]').bind('ajax:before', function () {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        });
    });
</script>

app/views/admin/addcities/index.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      旅游管理列表
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title>
      <h2><i class="icon-list-alt"></i> 旅游管理列表</h2>
    </div>
    <div class="box-content">
      <div class="form-actions">
        <div style="float: left">
          <%= link_to '添加城市', new_admin_addcity_path, :class => "btn btn-primary" %>
        </div>
      </div>
      <table class="table table-striped table-bordered bootstrap-datatable datatable">
        <thead>
        <tr>
          <th>ID</th>
          <th>分类</th>
          <th>城市</th>
          <th>添加旅游路线</th>
          <th>修改</th>
        </tr>
        </thead>
        <tbody>
        <% @jobs.each do |q| %>
            <tr>
              <td><%= q.id %></td>
              <td><%= q.question_category_name %></td>
              <td><%= q.title %></td>
              <td><%= link_to '添加旅游路线', admin_addcity_addtravels_path(q), :class => "btn btn-primary" %></td>
              <td><%= link_to '修改', edit_admin_addcity_path(q), :class => "btn btn-primary" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination pagination-centered">
        <ul>
          <%= paginate @jobs %>
        </ul>
      </div>
    </div>
  </div>
  <!--/span-->
</div><!--/row-->

app/views/admin/addcities/new.html.erb
<script>
    <% if flash[:error_msg]%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_addcities_path %>">旅游管理</a> <span class="divider">/</span>
    </li>
    <li>
      添加旅游城市
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 添加旅游城市</h2>
    </div>
    <div class="box-content">
      <%= form_for(:addcity, :url => admin_addcities_path, :method => :post, :html => {:id => "verifytitle"}) do |f| %>
          <legend>添加旅游城市</legend>
          <%= f.label "旅游分类：" %>
          <%= f.select :question_category_id, options_for_select(Addcity::QUESTION_CATEGORYS) %>
          <%= f.label "城市名称：" %>
          <%= f.text_field :title %>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">发布信息</button>
          </div>
      <% end %>
    </div>
  </div>
  <!--/span-->
</div>
<script src="/admin/js/jquery.validate.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $("#verifytitle").validate({
                rules: {
                    "addcity[title]": {
                        required: true
                    }
                },
                messages: {
                    "addcity[title]": {
                        required: "“请填写标题”"
                    }
                },
                errorClass: "error",
                highlight: function (element, errorClass) {
                    $(element).parent().parent().addClass(errorClass);
                },
                unhighlight: function (element, errorClass) {
                    $(element).parent().parent().removeClass(errorClass);
                },
                errorPlacement: function (error, element) {
                    error.appendTo(element.parent());
                },
                errorElement: "span"
            });
        });
    });
    $(document).ready(function () {
        $('form[data-remote]').bind('ajax:before', function () {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        });
    });
</script>

app/views/admin/addcities/show_travel.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= travel_admin_addcity_path %>">旅游路线管理</a> <span class="divider">/</span>
    </li>
    <li>
      浏览旅游内容
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 浏览旅游内容</h2>
    </div>
    <div class="box-content">
      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">旅游标题：
            <%= @hotline.title %>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>

      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">包团价格：
            <%= @hotline.price %>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>

      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">旅游图片：
            <%= image_tag @hotline.avatar.url(:show) %>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>

      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">旅游内容：
            <%= @hotline.description %>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>

      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">参考行程：
            <div class="form-actions">
              <%= @hotline.xingcheng.html_safe %>
            </div>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>


      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">费用说明：
            <div class="form-actions">
              <%= @hotline.feiyongshuoming.html_safe %>
            </div>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>

      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">温馨提示：
            <div class="form-actions">
              <%= @hotline.wenxintishi.html_safe %>
            </div>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>

      <li class="lineitem">
        <dl class="info fn-left">
          <dd class="desc">预订提示：
            <div class="form-actions">
              <%= @hotline.yudingtishi.html_safe %>
            </div>
          </dd>
          <div class="clear"></div>
        </dl>
      </li>
    </div>
  </div>
  <!--/span-->
</div>

app/views/admin/addcities/travel.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      旅游路线列表
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title>
      <h2><i class="icon-list-alt"></i> 旅游路线列表</h2>
    </div>
    <div class="form-actions">
      <div style="float: left">
        <%= link_to '添加旅游路线', add_travel_admin_addcity_path, :class => "btn btn-primary" %>
      </div>
    </div>
    <div class="box-content">
      <table class="table table-striped table-bordered bootstrap-datatable datatable">
        <thead>
        <tr>
          <th>ID</th>
          <th>标题</th>
          <th>价格</th>
          <th>图片</th>
          <th>时间</th>
          <th>浏览</th>
          <th>删除</th>
        </tr>
        </thead>
        <tbody>
        <% @travels.each do |q| %>
            <tr>
              <td><%= q.id %></td>
              <td><%= q.title %></td>
              <td><%= q.price %></td>
              <td><%= image_tag q.avatar.url(:thumb) %></td>
              <td class="center"><%= my_datetime_format q.created_at %></td>
              <td><%= link_to '浏览', show_travel_admin_addcity_path(q), :class => "btn btn-primary" %></td>
              <td><%= link_to '删除', admin_addcity_path(q), :method => "delete", data: {confirm: '确定要删除么？'}, :class => "btn btn-primary" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination pagination-centered">
        <ul>
          <%= paginate @travels %>
        </ul>
      </div>
    </div>
  </div>
  <!--/span-->
</div><!--/row-->