config/routes.rb
Travel::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root :to => "main#index"
  match '/login' => 'main#login', :via => :get
  match '/logout' => 'main#logout', :via => :get
  match '/signup' => 'main#signup', :via => :get
  resources :main do
    member do
      get 'show_tejia'
      get 'show_rm'
      get 'show_classic'
      get 'show_chujing'
      get 'show_domestic'
      get 'show_raider'
      get 'visa_show'
    end
    collection do
      post 'user_create'
      post 'login_check'
      get 'check_login'
      get 'visa'
    end
  end
  resources :destination_one do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :destination_two do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :destination_three do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :destination_four do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :destination_five do
    collection do
      post 'user_create'
    end
  end

  resources :destination_six

  resources :destination_seven

  resources :destination_eight do
    member do
      get 'gangao'
      get 'gentuan'
      get 'ziyouxing'
    end
  end
  resources :cities do
    collection do
      get 'xianggang'
      get 'aomen'
      get 'gangao'
      get 'feizhou'
      get 'remenchujing'
      get 'remenhaidao'
      get 'dongnanya'
      get 'yazhou'
      get 'ouzhou'
      get 'meizhou'
      get 'zhongdongfeizhou'
      get 'aozhou'
      get 'remenguonei'
      get 'huanan'
      get 'xinan'
      get 'huadong'
      get 'huazhong'
      get 'huabei'
      get 'xibu'
      get 'dongbei'
      get 'changchun'
    end
  end
  namespace :admin do
    match '' => 'accounts#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end

    resources :accounts do
      collection do
        post 'update_multiple'
      end
    end

    resources :announcements

    resources :raiders

    resources :one_cities do
      resources :exithots
      resources :domestics
      resources :jingdians
      resources :hotdoors
    end

    resources :citys do
      resources :tejia
      resources :raiders
      resources :recommends
      resources :gentuans
      resources :freelines
    end

    resources :three_cities do
      resources :three_tejia
      resources :three_raiders
      resources :three_recommends
      resources :three_gentuans
      resources :three_freelines
    end
    resources :companies do
      collection do
        get 'hotline'
        get 'customized_packages'
      end
    end
    resources :taiguos

    resources :hotels do
      resources :occupancy_hotels
    end

    resources :visas

    resources :addcities do
      resources :addtravels
    end
  end

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  scope :order_ct_desc, lambda { order("created_at DESC") }
  validates :title, :presence => {:message => "城市名称不能为空"}

  QUESTION_CATEGORYS = [["未分类", 0], ["香港酒店", 1], ["国内酒店", 2], ["国际酒店", 3]]

  has_many :occupancy_hotels

  def Hotel.question_category_name(category_id)
    QUESTION_CATEGORYS.each do |item|
      return item[0] if item[1] == category_id
    end
  end

  def question_category_name
    Hotel.question_category_name(self.question_category_id)
  end
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < Admin::MainController
  layout 'admin'

  def index
    @jobs = Hotel.order_ct_desc.page(params[:page]).per(10)
  end

  def new
    @job = Hotel.new
  end

  def create
    @job = Hotel.new(
        :title => params[:hotel][:title],
        :question_category_id => params[:hotel][:question_category_id]
    )
    if @job.save
      flash[:error_msg] = "创建成功"
      redirect_to admin_hotels_path and return
    else
      flash[:error_msg] = @job.errors.values.join(";    ")
      redirect_to :back and return
    end
  end

  def edit
    @job = Hotel.find(params[:id])
  end

  def update
    @category = Hotel.find(params[:id])
    update_category = @category.update_attributes(
        :title => params[:hotel][:title]
    )
    if update_category
      respond_to do |category|
        category.html {
          redirect_to admin_hotels_path and return
        }
      end
    end
  end
  #   删除
  def destroy
    @job = Hotel.find(params[:id])
    flash[:error_msg] = @job.destroy ? "删除成功" : "请稍后再试"
    redirect_to admin_hotels_path and return
  end
end

app/helpers/admin/hotels_helper.rb
module Admin::HotelsHelper
end

app/views/admin/hotels/edit.html.erb
<script>
    <% if flash[:error_msg]%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_hotels_path %>">城市管理</a> <span class="divider">/</span>
    </li>
    <li>
      修改城市
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 修改城市</h2>
    </div>
    <div class="box-content">
      <%= form_for(:hotel, :url => admin_hotel_path, :method => :put, :html => {:id => "verifytitle"}) do |f| %>
          <legend>修改城市</legend>
          <%= f.label "城市名称：" %>
          <%= f.text_field :title %>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">完成提交</button>
          </div>
      <% end %>
    </div>
  </div>
  <!--/span-->
</div>
<script src="/admin/js/jquery.validate.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $("#verifytitle").validate({
                rules: {
                    "hotel[title]": {
                        required: true
                    }
                },
                messages: {
                    "hotel[title]": {
                        required: "“请填写标题”"
                    }
                },
                errorClass: "error",
                highlight: function (element, errorClass) {
                    $(element).parent().parent().addClass(errorClass);
                },
                unhighlight: function (element, errorClass) {
                    $(element).parent().parent().removeClass(errorClass);
                },
                errorPlacement: function (error, element) {
                    error.appendTo(element.parent());
                },
                errorElement: "span"
            });
        });
    });
    $(document).ready(function () {
        $('form[data-remote]').bind('ajax:before', function () {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        });
    });
</script>

app/views/admin/hotels/index.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      城市列表
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title>
      <h2><i class="icon-list-alt"></i> 城市列表</h2>
    </div>
    <div class="box-content">
      <!--<div class="form-actions">-->
        <!--<div style="float: left">-->
          <!--<%#= link_to '添加城市', new_admin_hotel_path, :class => "btn btn-primary" %>-->
        <!--</div>-->
      <!--</div>-->
      <table class="table table-striped table-bordered bootstrap-datatable datatable">
        <thead>
        <tr>
          <th>ID</th>
          <th>分类</th>
          <th>城市</th>
          <th>酒店管理</th>
          <th>修改</th>
        </tr>
        </thead>
        <tbody>
        <% @jobs.each do |q| %>
            <tr>
              <td><%= q.id %></td>
              <td><%= q.question_category_name %></td>
              <td><%= q.title %></td>
              <td><%= link_to '设置酒店信息', admin_hotel_occupancy_hotels_path(q), :class => "btn btn-primary" %></td>
              <td><%= link_to '修改', edit_admin_hotel_path(q), :class => "btn btn-primary" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination pagination-centered">
        <ul>
          <%= paginate @jobs %>
        </ul>
      </div>
    </div>
  </div>
  <!--/span-->
</div><!--/row-->

app/views/admin/hotels/new.html.erb
<script>
    <% if flash[:error_msg]%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_hotels_path %>">城市管理</a> <span class="divider">/</span>
    </li>
    <li>
      添加城市
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 添加城市</h2>
    </div>
    <div class="box-content">
      <%= form_for(:hotel, :url => admin_hotels_path, :method => :post, :html => {:id => "verifytitle"}) do |f| %>
          <legend>添加公告</legend>
          <%= f.label "世界游分类：" %>
          <%= f.select :question_category_id, options_for_select(Hotel::QUESTION_CATEGORYS) %>
          <%= f.label "城市名称：" %>
          <%= f.text_field :title %>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">发布信息</button>
          </div>
      <% end %>
    </div>
  </div>
  <!--/span-->
</div>
<script src="/admin/js/jquery.validate.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $("#verifytitle").validate({
                rules: {
                    "hotel[title]": {
                        required: true
                    }
                },
                messages: {
                    "hotel[title]": {
                        required: "“请填写标题”"
                    }
                },
                errorClass: "error",
                highlight: function (element, errorClass) {
                    $(element).parent().parent().addClass(errorClass);
                },
                unhighlight: function (element, errorClass) {
                    $(element).parent().parent().removeClass(errorClass);
                },
                errorPlacement: function (error, element) {
                    error.appendTo(element.parent());
                },
                errorElement: "span"
            });
        });
    });
    $(document).ready(function () {
        $('form[data-remote]').bind('ajax:before', function () {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        });
    });
</script>